SampleClockin/Controllers/TimesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SampleClockin.Models;

namespace SampleClockin.Controllers
{
    public class TimesController : Controller
    {
        private TimeDataContext db = new TimeDataContext();

        // GET: Times
        public ActionResult Index()
        {




            return View(db.Times.ToList());
        }

        // GET: Times/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Time time = db.Times.Find(id);
            if (time == null)
            {
                return HttpNotFound();
            }
            return View(time);
        }
        // GET: Times/Create


        public ActionResult Create()
        {




            return View(new TimeDataContext());

        }

        // POST: Times/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id")] Time time, Time1 time1, TotalTime TotalTimes1, string buttonType)
        {


            if (buttonType == "ClockIn")
            {

                if (ModelState.IsValid)
                {
                    db.Times.Add(time);
                    db.SaveChanges();
                    return RedirectToAction("Create");
                }
                return View();
            }





            if (buttonType == "ClockOut")
            {
                if (ModelState.IsValid)
                {

                    db.Times1.Add(time1);
                    db.SaveChanges();

                    var query = from t in db.Times
                                join t1 in db.Times1 on t.ID equals t1.ID
                                select new { t.ClockIn, t1.ClockOut };

                    foreach (var group in query)
                    {

                        TotalTime nt = new TotalTime
                        {
                            TotalHours = (group.ClockOut - group.ClockIn),
                        };


                    }

                    db.TotalTimes.Add(TotalTimes1);
                    db.SaveChanges();

                    return RedirectToAction("Create");
                }

                return View();
            }

            //if (buttonType == "TotalTime")
            //{
            //    if (ModelState.IsValid)
            //    {
            //        //projects = db.Times.Join(db.Times1, s => s.Id, d => d.Id,
            //        //  (s, d) => new { ClockInTime = s.ClockIn, ClockOutTime = d.ClockOut })
            //        //    .Select(a => a.ClockInTime - a.ClockOutTime);

            //        db.TotalTimes.Add(projects);
            //        db.SaveChanges();
            //        return RedirectToAction("Create");
            //    }

            //    return View();
            //}

            //var ttime= 
            //    from Ctime in db.Times
            //    join  Otime in db.Times1 on Ctime.Id equals Otime.Id
            //    select new (NewTime => Ctime.ClockIn-Otime.ClockOut );

            //  var projects = db.Times.Join(db.Times1, s => s.Id, d => d.Id,
            //(s, d) => new { ClockInTime = s.ClockIn, ClockOutTime = d.ClockOut })
            //  .Select(a => a.ClockInTime - a.ClockOutTime);
            //  db.TotalTimes.Add(projects);

            return View();
        }

        // POST: Times/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ClockIn")] Time time)
        {
            if (ModelState.IsValid)
            {
                db.Entry(time).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(time);
        }

        // GET: Times/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Time time = db.Times.Find(id);
            if (time == null)
            {
                return HttpNotFound();
            }
            return View(time);
        }

        // POST: Times/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Time time = db.Times.Find(id);
            db.Times.Remove(time);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        //
        // GET: /Notes/_CreateNote - Partial view
        public ViewResult _ClockOut()
        {
            return View("_ClockOut");
        }









        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SampleClockin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MIES Employee</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function s(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},r=document,f=window,e="script",o=r.createElement(e),i,u;for(o.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config,r,f,e,o){var s=u&&u(config,r,f,e,o);return s!==!0&&t["_"+i](config,r,f,e,o),s}),t
        }({
            instrumentationKey:"ec3fd889-3fa2-4554-98d6-eba8f53dcb23"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MIES", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("TimeCard", "Create", "Times")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MIES</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>